[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[project]
name = "kitchen-sink"
version = "1!0+dev"
description = ""
authors = [{name = "Dagster Labs", email = "hello@dagsterlabs.com"}]
license = "Apache-2.0"
dependencies = [
    "dagster",
    "dagster-webserver",
    "dagster-airlift[core,in-airflow]",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.dg.project]
defs_module = "kitchen_sink.dagster_defs.inner_component_defs"
