[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[project]
name = "dagster-duckdb-pyspark"
version = "1!0+dev"
description = "Package for storing PySpark DataFrames in DuckDB."
authors = [{name = "Dagster Labs", email = "hello@dagsterlabs.com"}]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1!0+dev",
    "dagster-duckdb==1!0+dev",
    "pyspark>=4.1; python_version>='3.14'",
    "pyspark>=3.5,<4; python_version<'3.14'",
    "pandas<3.0.0",
    "pyarrow",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-duckb-pyspark"
