[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[project]
name = "with_wandb"
version = "1!0+dev"
dependencies = [
    "dagster",
    "dagster-wandb",
    "onnxruntime",
    "skl2onnx",
    "onnx>=1.13.0,<1.18.0",  # Ensure a version is installed that is protobuf 4 compatible
    "joblib",
    "torch",
    "torchvision",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[tool.dagster]
module_name = "with_wandb.definitions"
code_location_name = "with_wandb"
