[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[project]
name = "dagster-wandb"
version = "1!0+dev"
description = "Package for wandb Dagster components."
authors = [{name = "Dagster Labs", email = "hello@dagsterlabs.com"}]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1!0+dev",
    "wandb>=0.15.11,<1.0",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-wandb"

[project.optional-dependencies]
dev = [
    "cloudpickle",
    "joblib",
    "callee",
    "dill",
]
