[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[project]
name = "with_great_expectations"
version = "1!0+dev"
dependencies = [
    "dagster",
    "dagster-ge",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[tool.dagster]
module_name = "with_great_expectations.definitions"
code_location_name = "with_great_expectations"
