[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["dbt_example"]

[project]
name = "starlift-demo"
version = "1!0+dev"
dependencies = [
    "dagster",
    "dagster-webserver",
    "dagster-airlift[core,in-airflow]",
    "dagster-dbt",
    "dbt-duckdb",
    "pandas",
    "apache-airflow<3.0.0",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.dagster]
module_name = "dbt_example.definitions"
