[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[project]
name = "dagster-deltalake"
version = "1!0+dev"
description = "Package for Deltalake-specific Dagster framework op and resource components."
authors = [{name = "Elementl", email = "hello@elementl.com"}]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
dependencies = [
    "deltalake>=1.0.0",
    "pyarrow",
    "dagster==1!0+dev",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-deltalake"

[project.optional-dependencies]
pandas = [
    "pandas<3.0.0",
]
