[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dbt-example"
version = "1!0+dev"
dependencies = [
    "dagster==1!0+dev",
    "dagster-webserver==1!0+dev",
    "dagster-airlift[core,in-airflow]==1!0+dev",
    "dbt-duckdb",
    "pandas",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
