[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "project_fully_featured"
version = "1!0+dev"
authors = [{name = "Dagster Labs", email = "hello@dagsterlabs.com"}]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = [
    "aiobotocore",
    "dagster",
    "dagster-aws",
    "dagster-dbt",
    "dagster-pandas",
    "dagster-pyspark",
    "dagster-slack",
    "dagster-postgres",
    "dbt-duckdb",
    "dbt-snowflake",
    "duckdb!=0.3.3, <= 6.0.0",  # missing wheels
    "pandas",
    "pyarrow>=4.0.0",
    "pyspark<4",
    "requests",
    "gcsfs",
    "fsspec",
    "s3fs",
    "scipy",
    "scikit-learn",
    "sqlalchemy!=1.4.42",  # workaround for https://github.com/snowflakedb/snowflake-sqlalchemy/issues/350
    "snowflake-sqlalchemy<1.5.2",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]
tests = ["mypy", "pylint", "pytest"]

[tool.dagster]
module_name = "project_fully_featured.definitions"
code_location_name = "project_fully_featured"

[tool.setuptools.packages.find]
exclude = ["test*"]

[tool.setuptools.package-data]
project_fully_featured = ["hacker_news_dbt/*"]
